[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
lannister_bank_token_sale = "D6dvAzWWpJBtvSe1b2NzZjvqWfxeYAsimbyi2DRvCzQk"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/marcelofeitoza/.config/solana/id.json"

[scripts]
test = "yarn run jest --preset ts-jest"
